### PR TITLE
"greg" version of firewalker shoe code

### PR DESCRIPTION
**Pull request by gregmarra**
A few improvements to the firewalker code
- Adds DEBUG option to allow previewing without wearing.
- Changes how LED indices are mapped to allow for LED strip running other way around shoe. 
- Creates MODE_RAINBOW_FALLBACK to have a default mode for if sensors break.
- Adds MODE_GREEN because Greg's other glow stuff is always green.
- Some formatting changes because I don't like when logical chunks of stuff don't have linebreaks between them.

### CODE REVIEW

**Comment by Bhagan77** [comment]
Thank you for this code! So much better then the code provided by Adafruit.  I was having all kinds of problems mainly on the shoe where the LED's ran opposite direction.  The mode change, and the better way to calculate the step (pressure/time) is excellent!!

**Comment by jeffsharris** [comment]
Thanks. Glad you're liking it :)

The calibration change ended up being really important because the pressure
sensitivity seems to arbitrarily drift over time.

On Wed, Oct 22, 2014 at 12:50 PM, Bhagan77 notifications@github.com wrote:

> Thank you for this code! So much better then the code provided by
> Adafruit. I was having all kinds of problems mainly on the shoe where the
> LED's ran opposite direction. The mode change, and the better way to
> calculate the step (pressure/time) is excellent!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeffsharris/firewalker/pull/2#issuecomment-60144163.

## 

Jeff Harris | 3625 17th St, CA 94114 | (650) 265-1224

**Comment by Bhagan77** [comment]
It definitely drifted over time, and it was a very short time.  I'm not
much of a coder, more of a hardware guy (I also do a huge RGB light display
for holidays) but I was wondering, is this code, mainly with the power
on/off function to change modes easily adaptable to other devices?  I built
the steampunk goggles too and they have a code that uses the sensor that
positions the LEDs on the neopixel ring based on direction, also they have
just a rainbow pattern code.  It's a pain to connect it to USB everytime I
want to change it.

On Wed, Oct 22, 2014 at 3:53 PM, Jeff Harris notifications@github.com
wrote:

> Thanks. Glad you're liking it :)
> 
> The calibration change ended up being really important because the
> pressure
> sensitivity seems to arbitrarily drift over time.
> 
> On Wed, Oct 22, 2014 at 12:50 PM, Bhagan77 notifications@github.com
> wrote:
> 
> > Thank you for this code! So much better then the code provided by
> > Adafruit. I was having all kinds of problems mainly on the shoe where
> > the
> > LED's ran opposite direction. The mode change, and the better way to
> > calculate the step (pressure/time) is excellent!!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jeffsharris/firewalker/pull/2#issuecomment-60144163.
> 
> ## 
> 
> Jeff Harris | 3625 17th St, CA 94114 | (650) 265-1224
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeffsharris/firewalker/pull/2#issuecomment-60144595.

## 

_Bryan Hagan Jr_

All Seasons Heating & Cooling
1510 Caton Center Drive - Suite G
Baltimore, MD. 21227

Tel: 443-304-2379
Fax: 443-304-2392
Mobile: 443-995-8998
Web: www.CallAllSeasons.com
@ bryanjr@allseasonsmd.com

**Comment by jeffsharris** [comment]
The mode changing code
https://github.com/jeffsharris/firewalker/blob/master/left/left.ino#L83
should work for other Arduino devices. It's basically storing the mode
information in the same memory that Arduino uses to store the program
itself.

On Wed, Oct 22, 2014 at 7:04 PM, Bhagan77 notifications@github.com wrote:

> It definitely drifted over time, and it was a very short time. I'm not
> much of a coder, more of a hardware guy (I also do a huge RGB light
> display
> for holidays) but I was wondering, is this code, mainly with the power
> on/off function to change modes easily adaptable to other devices? I built
> the steampunk goggles too and they have a code that uses the sensor that
> positions the LEDs on the neopixel ring based on direction, also they have
> just a rainbow pattern code. It's a pain to connect it to USB everytime I
> want to change it.
> 
> On Wed, Oct 22, 2014 at 3:53 PM, Jeff Harris notifications@github.com
> wrote:
> 
> > Thanks. Glad you're liking it :)
> > 
> > The calibration change ended up being really important because the
> > pressure
> > sensitivity seems to arbitrarily drift over time.
> > 
> > On Wed, Oct 22, 2014 at 12:50 PM, Bhagan77 notifications@github.com
> > wrote:
> > 
> > > Thank you for this code! So much better then the code provided by
> > > Adafruit. I was having all kinds of problems mainly on the shoe where
> > > the
> > > LED's ran opposite direction. The mode change, and the better way to
> > > calculate the step (pressure/time) is excellent!!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/jeffsharris/firewalker/pull/2#issuecomment-60144163>.
> > 
> > ## 
> > 
> > Jeff Harris | 3625 17th St, CA 94114 | (650) 265-1224
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jeffsharris/firewalker/pull/2#issuecomment-60144595.
> 
> ## 
> 
> _Bryan Hagan Jr_
> 
> All Seasons Heating & Cooling
> 1510 Caton Center Drive - Suite G
> Baltimore, MD. 21227
> 
> Tel: 443-304-2379
> Fax: 443-304-2392
> Mobile: 443-995-8998
> Web: www.CallAllSeasons.com
> @ bryanjr@allseasonsmd.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeffsharris/firewalker/pull/2#issuecomment-60183218.

## 

Jeff Harris | 3625 17th St, CA 94114 | (650) 265-1224

**Comment by Bhagan77** [comment]
Ok cool thanks. Definitely need to figure out a better sensor. This velostat after wearing for a couple hours goes wonky. Like the fire mode sometimes doesn't want to add the white and yellow. I'm thinking cause the velostat has lost sensitivity.

**Comment by gregmarra** [comment]
@jeffsharris  do you want to merge this pull?

**Comment by pwindom** [comment]
Hey Greg I love you mode change code, it also makes the firewalkers look much better! I am having an issue with the RAINBOW_FALLBACK if I include this code in the program, more so the prototype all of the modes go directly into the rainbow cycle AFTER displaying the modes actual 3 colors.

**Comment by gregmarra** [comment]
Thanks! The mode code was a collaboration with the others here, but is
great.

Let make sure I understand the problem: no matter what color mode you pick,
it always goes into the rainbow cycle? I'm not sure what would be causing
that, have you tried looking at a debug print over the serial to see what
mode you're in? That'd be my first instinct.

**Comment by pwindom** [comment]
Yes, all of the modes will display their proper colors. Then they will go into the rainbow cycle which throws me off. I am a beginner at best at C college classes are a joke. I will take a look at whats going on over the serial when I return home. I tried using your exact program with MODE_GREEN as well and it still did the exact same thing.. weird situation.

**Comment by gregmarra** [comment]
I'm on my phone so can't investigate too much right now. Check out the
debug flag in the code and see if that helps you understand what is going
on. It should give you an example of how to print things to the serial
monitor you can open from the arduino app.

**Pull request closed without merging**
